apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - configmap.yaml
  - deployment.yaml

commonLabels:
  app: argocd-metrics-server
  app.kubernetes.io/name: argocd-metrics-server
  app.kubernetes.io/component: metrics-server