apiVersion: v1
kind: Service
metadata:
  name: argocd-metrics-server
  labels:
    app.kubernetes.io/name: argocd-metrics-server
    app.kubernetes.io/part-of: argocd
spec:
  ports:
  - name: metrics
    port: 9003
    protocol: TCP
    targetPort: 9003
  selector:
    app: argocd-metrics-server